<?php

define('STUDENT_CRM_DEFAULT_TYPE', 'note');

/**
 * @file
 * Code for the Student CRM Activity feature.
 */

include_once('student_crm_activity.features.inc');

/**
 * Implements hook_block_info().
 */
function student_crm_activity_block_info() {
  $blocks['student_crm_activity_create'] = array('info' => 'Create activity form');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function student_crm_activity_block_view($delta) {
  if($delta == 'student_crm_activity_create') {
    return array('subject' => 'Add a note',
                 'content' => drupal_get_form('student_crm_activity_create'));
  }
}

/**
 * Implements hook_theme_registry_alter().
 */

/**
 * Create activity form.
 */
function student_crm_activity_create($form, $form_state) {
  drupal_add_js(drupal_get_path('module', 'student_crm_activity') .'/js/jquery.color.js');
  drupal_add_js(drupal_get_path('module', 'student_crm_activity') .'/js/student_crm_activity.form.js');
  global $user;
  $form = array();
  
  $form['#prefix'] = '<div id="activity-sub-form">';
  $form['#suffix'] = '</div>';
  
  $entity = array();
  
  if($form_state['values']['entity']) {
    $entity = $form_state['values']['entity'];
  }
  else {
    if($case = menu_get_object('crm_case', 2)) {
      $entity['type'] = 'crm_case';
      $entity['bundle'] = $case->type;
      $entity['id'] = $case->cid;   
    }
    if($contact = menu_get_object('crm_contact', 2)) {
      $entity['type'] = 'crm_contact';
      $entity['bundle'] = $contact->type;
      $entity['id'] = $contact->contact_id;   
    }
  }    
  $form['entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );
  
  $types = crm_activity_get_types();
  $options = array();
  foreach($types as $type) {
    $restrict = variable_get('student_crm_activity_restrict_'. $type->type, FALSE);
    if((user_access('administer crm activities') 
       || user_access("edit any $type->type crm_activity")) && (
        !$restrict || 
        $restrict[$entity['type'] .':'. $entity['bundle']] || 
        $restrict[$entity['type'] .':*'])
        ) {
      $options[$type->type] = $type->label;
    }
  }
  if(!count($options)) {
    $form = array();
    $form['message'] = array(
      '#markup' => '<h3 class="empty">'. t('You cannot create a note on this page.') .'</h3>',
    );
    return $form;
  }
  
  $form['activity_type'] = array(
    '#type' => 'select',
    '#title' => 'Note type',
    '#options' => $options,
    '#default_value' => STUDENT_CRM_DEFAULT_TYPE,
    '#ajax' => array(
			'callback' => 'student_crm_activity_activity_form',
			'wrapper' => 'activity-sub-form',
			'progress' => array(
				'type' => 'throbber',
				'message' => 'Getting form',
			),
		),
		'#weight' => -20,
  );
  
  $activity_type = (isset($form_state['values']['activity_type'])) 
                   ? $form_state['values']['activity_type'] 
                   : STUDENT_CRM_DEFAULT_TYPE;
  $crm_activity = crm_activity_create(array('type' => $activity_type));
  
  $form_state['crm_activity'] = $crm_activity;
  field_attach_form('crm_activity', $crm_activity, $form, $form_state);
  
  $form['form-actions'] = array(
    '#type' => 'actions',
  );
  
  $form['form-actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save note',
    '#ajax' => array(
      'callback' => 'student_crm_activity_activity_form',
      'wrapper' => 'activity-sub-form',
      'name' => 'submit1',
    ),
  );
  
  return $form;
}

/**
 * Ajax callback to redraw form when the note type changes.
 */
function student_crm_activity_activity_form(&$form, $form_state) {
	return $form;
}

/**
 * Create activity form submit.
 */
function student_crm_activity_create_submit($form, $form_state) {
  global $user;
  $crm_activity = entity_ui_controller('crm_activity')->entityFormSubmitBuildEntity($form, $form_state);
  $crm_activity->created = time();
  $crm_activity->changed = time();
  $crm_activity->uid = $user->uid;
  $activity_id = crm_activity_save($crm_activity);
  $relation = relation_create('crm_activity', array(
                array('entity_type' => 'crm_activity',
                       'entity_bundle' => $crm_activity->type,
                       'entity_id' => $crm_activity->crm_activity_id,
                       'r_index' => 0,
                       ),
                  array('entity_type' => $form_state['values']['entity']['type'],
                         'entity_bundle' => $form_state['values']['entity']['bundle'], 
                         'entity_id' => $form_state['values']['entity']['id'],
                         'r_index' => 1,
                         ))
             );
  relation_save($relation);
}

/**
 * Alter the activity type form to add in options for restricitng posting to certain
 * entity/bundle types.
 */
function student_crm_activity_form_crm_activity_type_form_alter(&$form, $form_state) {
  
  $form['entity_restrictions'] = array(
    '#type' => 'fieldset',
    '#title' => 'Advanced options',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  
  $bundles = array();
  foreach (entity_get_info() as $entity_type => $entity) {
    $bundles[$entity['label']]["$entity_type:*"] = 'all ' . $entity['label'] . ' bundles';
    $counter += 2;
    if (isset($entity['bundles'])) {
      foreach ($entity['bundles'] as $bundle_id => $bundle) {
        $bundles[$entity['label']]["$entity_type:$bundle_id"] = $bundle['label'];
        $counter++;
      }
    }
  }
  
  $form['entity_restrictions']['entity_types'] = array(
    '#type' => 'select',
    '#title' => 'Restrict to only entity types',
    '#options' => $bundles,
    '#default_value' => variable_get('student_crm_activity_restrict_'. $form['type']['#default_value'], array()),
    '#multiple' => TRUE,
  );
  
  $form['#submit'][] = 'student_crm_activity_form_crm_activity_type_form_alter_submit';
}

/**
 * Form submit callback for editing activity types.
 */
function student_crm_activity_form_crm_activity_type_form_alter_submit($form, $form_state) {
  $save = false;
  foreach($form_state['values']['entity_types'] as $type) {
    if($type) {
      $save = $form_state['values']['entity_types'];
      break;
    }
  }
  variable_set('student_crm_activity_restrict_'. $form['type']['#default_value'], $save);
}

/**
 * Implements hook_feeds_plugins().
 */
function student_crm_activity_feeds_plugins() {
  $info['StudentCRMActivityFeedsProcessor'] = array(
    'name' => 'CRM Activity processor',
    'description' => 'Add and update activities attached to contacts.',
    'help' => 'Create and update activities from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'StudentCRMActivityFeedsProcessor',
      'file' => 'StudentCRMActivityFeedsProcessor.inc',
      'path' => drupal_get_path('module', 'student_crm_activity') . '/plugins',
    ),
  );
  return $info;
}

/*
 * Implements hook_enable().
 */
function student_crm_activity_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}