<?php

function student_crm_activity_install() {
  $note = entity_create('crm_core_activity_type', array(
    'type' => 'note',
    'label' => t('Note'),
    'description' => t('A simple actiity type that stores a note'), 
  ));
  crm_core_activity_type_save($note);
  
  //Delete the standard activity types.
  db_delete('crm_core_activity_type')
    ->condition('type', array('phone_call', 'meeting'))
    ->execute();
}