<?php
/**
 * @file
 * Code for the CRM courses feature.
 */

include_once('crm_courses.features.inc');

/**
 * Implements hook_feeds_plugins().
 */
function crm_courses_feeds_plugins() {
  $info['CRMFeedsCourseEnrollmentProcessor'] = array(
    'name' => 'CRM Course enrollment processor',
    'description' => 'Add and update course enrollment records.',
    'help' => 'Create and update enrollment records from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'CRMFeedsCourseEnrollmentProcessor',
      'file' => 'CRMFeedsCourseEnrollmentProcessor.inc',
      'path' => drupal_get_path('module', 'crm_courses') . '/plugins',
    ),
  );
  return $info;
}

/*
 * Implements hook_enable().
 */
function crm_courses_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Implements hook_permission().
 */
function crm_courses_permission() {
  return array(
    'access course enrollment information' => array(
      'title' => t('Access course enrollment information'),
      'description' => t('User can view information about courses.'),
    ),
  );
}

/**
 * Implements hook_crm_student_admin_links().
 */
function crm_courses_crm_student_admin_links() {
  return array(
    'crm_courses_terms' => array(
      'group' => t('Courses'),
      'title' => t('Manage terms'),
      'description' => t('View and manage the list of terms.'),
      'href' => 'admin/structure/taxonomy/term',
    ),
  );
}