<?php
/**
 * @file
 * Code for the Student CRM Activity Mailer feature.
 */

include_once('student_crm_activity_mailer.features.inc');

/**
 * Implements hook_feeds_plugins().
 */
function student_crm_activity_mailer_feeds_plugins() {
  $info['StudentCRMActivityEmailFeedsProcessor'] = array(
    'name' => 'CRM Email Activity processor',
    'description' => 'Create email activities.',
    'help' => 'Only useful for emailed activities, this will convert an email to a special activity type.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'StudentCRMActivityEmailFeedsProcessor',
      'file' => 'StudentCRMActivityEmailFeedsProcessor.inc',
      'path' => drupal_get_path('module', 'student_crm_activity_mailer') . '/plugins',
    ),
  );
  return $info;
}

/**
 * Alter the create case form to hide email activities.
 */
function student_crm_activity_mailer_form_student_crm_activity_create_alter(&$form, $form_state) {
  unset($form['activity_type']['#options']['email_activity']);
}