<?php

/**
 * Implements hook_install().
 */
function crm_student_install() {
  module_load_include('inc', 'menu');
  menu_rebuild();
  cache_clear_all();
  
  $path = 'public://default_images';
  file_prepare_directory($path, FILE_CREATE_DIRECTORY);
  //Install the generic person outline.
  $file = (object)array('uri' => 
                        drupal_get_path('module', 'crm_student') .'/images/generic_person.png');
file_move($file, 'public://default_images/generic_person.png');
}