<?php

include_once('crm_student.features.inc');

/**
 * @file
 */

/**
 * Implements hook_init().
 */
function crm_student_init() {
  drupal_add_css(drupal_get_path('module', 'crm_student') . '/css/crm_student.css');
  drupal_add_js(drupal_get_path('module', 'crm_student') . '/js/crm_student.easycopy.js');
}

/**
 * Implements hook_menu().
 */
function crm_student_menu() {
  $items = array();
  
  $items['crm/home'] = array(
    'title' => 'Home page',
    'page callback' => 'crm_student_home_page',
    'access callback' => 'crm_student_homepage_access',
  );
  
  $items['admin/config/crm'] = array(
    'title' => 'Student CRM',
    'description' => 'Generic settings for the student CRM site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_student_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'crm_student.admin.inc',
  );
  
  $items['admin/config/crm/settings'] = array(
    'title' => 'General Settings',
    'description' => 'Generic settings for the student CRM site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_student_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'crm_student.admin.inc',
  );
  
  return $items;
}

/**
 * Empty page callback for CRM homepage
 */
function crm_student_home_page() {
  drupal_set_title(variable_get('site_name', 'Student CRM'));
  return '';
}

/**
 * Always true homepage access callback.
 */
function crm_student_homepage_access() {
  return TRUE;
}

/**
 * Implements hook_block_info().
 */
function crm_student_block_info() {
  $blocks['crm_student_search'] = array('info' => 'Student CRM search box');
  $blocks['crm_student_welcome'] = array('info' => 'Generic welcome message');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_student_block_view($delta) {
  if ($delta == 'crm_student_search') {
    return array('content' => drupal_get_form('_crm_student_search_form'));  
  }
  if ($delta == 'crm_student_welcome') {
    $message = variable_get('crm_student_welcome_page', '');
    return array('content' => check_markup($message['value'], $message['format']));
  }
}

function crm_student_block_view_alter(&$data, $block) {
  if ($block->module == 'menu' && $block->delta == 'menu-crm-navigation') {
    unset($data['subject']);
  }
}

/**
 * A generic search form
 */
function _crm_student_search_form() {
  $form = array();

  $form['#attributes']['class'][] = 'site-search-form';
  $form['search'] = array(
    '#type' => 'textfield',
    '#title' => '<span class="element-invisible">Search for students</span>',
    '#attributes' => array('class' => array('search-box'),
                           'placeholder' => 'Search'),
    '#default_value' => (isset($_GET['name'])) ? check_plain($_GET['name']) : '',
  );
  
  $form['#info']['contact_name_value']['label']['#attributes']['classs'][] = 'element-invisible';
  /**
  * $form['advanced'] = array(
  *   '#markup' => l('Advanced search', 'crm/search'),
  * );
  */
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#attributes' => array('class' => array('element-invisible')),
  );
  
  return $form;
}

/**
 * A generic search form
 */
function _crm_student_search_form_submit($form, &$form_state) {
  drupal_goto('crm/search', array('query' => array('name' => $form_state['values']['search'])));
}