<?php

include_once('crm_student.features.inc');

/**
 * @file
 */

function crm_student_init() {
  drupal_add_css(drupal_get_path('module', 'crm_student') .'/css/crm_student.css');
}

/**
 * Implements hook_block_info().
 */
function crm_student_block_info() {
	$blocks['crm_student_search'] = array('info' => 'Student CRM search box');
	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_student_block_view($delta) {
	if($delta == 'crm_student_search') {
		return array('content' => drupal_get_form('_crm_student_search_form'));	
	}
}

function crm_student_block_view_alter(&$data, $block) {
  if($block->module == 'menu' && $block->delta == 'menu-crm-navigation') {
    unset($data['subject']);
  }
}

/**
 * A generic search form
 */
function _crm_student_search_form() {
	$form = array();

	$form['#attributes']['class'][] = 'site-search-form';
	$form['search'] = array(
		'#type' => 'textfield',
		'#title' => '<span class="element-invisible">Search for students</span>',
		'#attributes' => array('class' => array('search-box'),
													 'placeholder' => 'Search'),
		'#default_value' => (isset($_GET['name'])) ? check_plain($_GET['name']) : '',
	);
	
	$form['#info']['contact_name_value']['label']['#attributes']['classs'][] = 'element-invisible';
	
	$form['advanced'] = array(
		'#markup' => l('Advanced search', 'crm/search'),
	);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Search',
		'#attributes' => array('class' => array('element-invisible')),
	);
	
	return $form;
}

/**
 * A generic search form
 */
function _crm_student_search_form_submit($form, &$form_state) {
  drupal_goto('crm/search', array('query' => array('name' => $form_state['values']['search'])));
}