<?php
/**
 * @file
 * Code for the Student CRM Webform feature.
 */

include_once('student_crm_webform.features.inc');

function student_crm_webform_menu() {
  $items = array();
  
  $items['crm/webform/%/%/%node/%'] = array(
    'page callback' => 'student_crm_webform_complete_form',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array(2, 3, 4, 5),
    'access callback' => 'student_crm_webform_complete_form_access',
  );
  
  return $items;
}

function student_crm_webform_complete_form_access($entity_type, $entity_id, $webform, $key) {
  if(!user_access('complete crm webforms')) {
    return FALSE;
  }
  if($key != _student_crm_webform_generate_key($entity_type, $entity_id, $webform->nid)) {
    return FALSE;
  }
  return TRUE;
}

function student_crm_webform_complete_form($entity_type, $entity_id, $webform) {
  
}

function _student_crm_webform_generate_key($entity_type, $entity_id, $webform_nid) {
  return drupal_hmac_base64($entity_type .':'. $entity_id .':'. $webform_nid .':'. drupal_get_hash_salt());
}

/**
 * Implements hook_permission().
 */
function student_crm_webform_permission() {
  return array('complete crm webforms' => array(
              'title' => t('Fill out webforms attached to CRM entities'),
              'description' => t('Allowed to complete webforms that are later attached to CRM contacts or cases.')));
}