<?php
/**
 * @file
 * Code for the Student CRM GPA feature.
 */

include_once('student_crm_gpa.features.inc');

/**
 * Implements hook_init().
 */
function student_crm_gpa_init() {
  drupal_add_css(drupal_get_path('module', 'student_crm_gpa') . '/css/student_crm_gpa.css');
}

/**
 * Implements hook_feeds_plugins().
 */
function student_crm_gpa_feeds_plugins() {
  $info['CRMFeedsGPAProcessor'] = array(
    'name' => 'Student GPA processor',
    'description' => 'Add and update GPA records.',
    'help' => 'Create and update GPA records from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'CRMFeedsGPAProcessor',
      'file' => 'CRMFeedsGPAProcessor.inc',
      'path' => drupal_get_path('module', 'student_crm_gpa') . '/plugins',
    ),
  );
  return $info;
}

/*
 * Implements hook_enable().
 */
function student_crm_gpa_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Implements hook_permission().
 */
function student_crm_gpa_permission() {
  return array('view gpa data' => array(
              'title' => t('View GPA data'),
              'description' => t('User is able to view GPA data on students.'),
            ),
          );
}

/**
 * Implements hook_block_info().
 */
function student_crm_gpa_block_info() {
  $blocks['student_crm_gpa_graph'] = array('info' => 'Student GPA History Graph');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function student_crm_gpa_block_view($delta) {
  switch ($delta) {
    case 'student_crm_gpa_graph':
      drupal_add_js(array('contact_id' => arg(2)), 'setting');
      drupal_add_js(drupal_get_path('module', 'student_crm_gpa') . '/js/student_crm_gpa.chart.js');
      return array('title' => 'GPA History', 'content' => crm_student_draw_chart(array('id' => 'gpa-chart')));
      break;
  }
}