<?php
/**
 * @file
 * Code for the CRM Tasks feature.
 */

include_once('crm_tasks.features.inc');

/**
 * Implements hook_menu().
 */
function crm_tasks_menu() {
  $items = array();
  
  $items['crm/tasks/mark/%/%'] = array(
    'title' => 'Mark task',
    'page callback' => 'crm_tasks_mark_task',
    'page arguments' => array(3, 4),
    'access callback' => 'crm_tasks_mark_task_access',
    'access arguments' => array(3),
  );
  
  return $items;
}

/**
 * Menu access callback for marking tasks.
 */
function crm_tasks_mark_task_access($task) {
  $relation = relation_load($task);
  global $user;
  if($relation) {
    return ($relation->uid == $user->uid);
  }
  return FALSE;
}

/**
 * Page callback to mark a task.
 */
function crm_tasks_mark_task($task, $status) {
  $relation = relation_load($task);
  $mark = ($status == 'mark') ? 1 : 0;
  $language = ($relation->language) ? $relation->language : LANGUAGE_NONE;
  $relation->field_task_complete[$language][0]['value'] = $mark;
  relation_save($relation);
  drupal_json_output(array('success' => true, 'mark' => $mark, 'relation' => $relation->rid));
}

/**
 * Implements hook_block_info().
 */
function crm_tasks_block_info() {
  $blocks['crm_tasks_new_task'] = array('info' => 'New task form');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_tasks_block_view($delta) {
  if($delta == 'crm_tasks_new_task' && user_access('maintain own task list')) {
    $modal_link = l('Add to tasks', null, array('fragment' => 'edit-task-modal', 'external' => TRUE, 'attributes' => array('id' => 'show-add-tasks')));
    return array('content' => $modal_link . drupal_render(drupal_get_form('crm_tasks_create_task_form')));
  }
}

/**
 * Create task form
 */
function crm_tasks_create_task_form() {
  drupal_add_js(drupal_get_path('module', 'crm_tasks') .'/js/crm_tasks.js');
  drupal_add_css(drupal_get_path('module', 'crm_tasks') .'/css/crm_tasks.css');
  $form = array();
  
  $form['#attributes']['id'] = 'edit-task-modal';
  
  $form['target_id'] = array(
    '#type' => 'hidden'
  );
  
  $form['target_bundle'] = array(
    '#type' => 'hidden'
  );
  
  $form['target_entity'] = array(
    '#type' => 'hidden'
  );
  
  if($contact = _crm_history_get_contact()) {
    $form['target_id']['#value'] = $contact->contact_id;
    $form['target_bundle']['#value'] = $contact->type;
    $form['target_entity']['#value'] = 'crm_contact';
  }
  
  $form['date'] = array(
    '#type' => 'date_popup',
    '#title' => 'Due date',
    '#date_format' => 'Y-m-d',
  );
  
  $form['note'] = array(
    '#type' => 'textfield',
    '#title' => 'Note',
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save task',
  );
  
  $form['cancel'] = array(
    '#markup' => l('Cancel', '', array('fragment' => 'task-cancel', 'external' => TRUE, 'attributes' => array('id' => 'task-cancel'))),
  );
  
  return $form;
}

/**
 * Create task form submit
 */
function crm_tasks_create_task_form_submit($form, $form_state) {
  global $user;
  $relation = relation_construct('crm_task', array(
                  array('entity_type' => 'user',
                         'entity_bundle' => 'user',
                         'entity_id' => $user->uid,
                         'r_index' => 0,
                         ),
                  array('entity_type' => $form_state['values']['target_entity'],
                         'entity_bundle' => $form_state['values']['target_bundle'], 
                         'entity_id' => $form_state['values']['target_id'],
                         'r_index' => 1,
                         ))
               );
  $rid = relation_save($relation);
  $relation = relation_load($rid);
  $language = ($relation->language) ? $relation->language : LANGUAGE_NONE;
  $relation->field_task_due[$language][0]['value'] = $form_state['values']['date'];
  $relation->field_task_note[$language][0]['value'] = $form_state['values']['note'];
  relation_save($relation);
  drupal_set_message(t('Your task has been created.'));
}

/**
 * Implements hook_permission().
 */
function crm_tasks_permission() {
  return array(
    'maintain own task list' => array(
      'title' => t('Maintain own task list'),
      'description' => t('User can add and maintain their own list of tasks.'),
    ),
  );
}