<?php
/**
 * @file
 * Code for the CRM Tasks feature.
 */

include_once('crm_tasks.features.inc');

/**
 * Implements hook_menu().
 */
function crm_tasks_menu() {
  $items = array();
  
  $items['crm/tasks/mark/%/%'] = array(
    'title' => 'Mark task',
    'page callback' => 'crm_tasks_mark_task',
    'page arguments' => array(3, 4),
    'access callback' => 'crm_tasks_mark_task_access',
    'access arguments' => array(3),
  );
  
  $items['ajax/crm/tasks/user-autocomplete'] = array(
    'title' => 'Username autocomplete',
    'page callback' => 'crm_tasks_username_autocomplete',
    'access arguments' => array('access user profiles'),
  );
  
  return $items;
}

/**
 * Autocomplete callback to return users who can have a task list.
 */
function crm_tasks_username_autocomplete($string = '') {
  $matches = array();
  if ($string) {
    $result = db_select('users')->fields('users', array('uid', 'name'))->condition('name', db_like($string) . '%', 'LIKE')->range(0, 100)->execute();
    foreach ($result as $user) {
      if(user_access('maintain own task list', user_load($user->uid))) {
        $matches[$user->name] = check_plain($user->name);
      }
    }
    $matches = array_chunk($matches, 10, TRUE);
    $matches = $matches[0];
  }

  drupal_json_output($matches);
}


/**
 * Menu access callback for marking tasks.
 */
function crm_tasks_mark_task_access($task) {
  $relation = relation_load($task);
  global $user;
  if($relation) {
    return ($relation->uid == $user->uid);
  }
  return FALSE;
}

/**
 * Page callback to mark a task.
 */
function crm_tasks_mark_task($task, $status) {
  $relation = relation_load($task);
  $mark = ($status == 'mark') ? 1 : 0;
  $language = ($relation->language) ? $relation->language : LANGUAGE_NONE;
  $relation->field_task_complete[$language][0]['value'] = $mark;
  relation_save($relation);
  drupal_json_output(array('success' => true, 'mark' => $mark, 'relation' => $relation->rid));
}

/**
 * Implements hook_block_info().
 */
function crm_tasks_block_info() {
  $blocks['crm_tasks_new_task'] = array('info' => 'New task form');
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function crm_tasks_block_view($delta) {
  if($delta == 'crm_tasks_new_task' && user_access('maintain own task list')) {
    $modal_link = l('Add to tasks', null, array('fragment' => 'edit-task-modal', 'external' => TRUE, 'attributes' => array('id' => 'show-add-tasks')));
    return array('content' => $modal_link . drupal_render(drupal_get_form('crm_tasks_create_task_form')));
  }
}

/**
 * Create task form
 */
function crm_tasks_create_task_form() {
  drupal_add_js(drupal_get_path('module', 'crm_tasks') .'/js/crm_tasks.js');
  drupal_add_css(drupal_get_path('module', 'crm_tasks') .'/css/crm_tasks.css');
  $form = array();
  
  $form['#attributes']['id'] = 'edit-task-modal';
  
  $form['target_id'] = array(
    '#type' => 'hidden'
  );
  
  $form['target_bundle'] = array(
    '#type' => 'hidden'
  );
  
  $form['target_entity'] = array(
    '#type' => 'hidden'
  );
  
  if($contact = menu_get_object('crm_core_contact', 2)) {
    $form['target_id']['#value'] = $contact->contact_id;
    $form['target_bundle']['#value'] = $contact->type;
    $form['target_entity']['#value'] = 'crm_core_contact';
  }
  if($case = menu_get_object('crm_case', 2)) {
    $form['target_id']['#value'] = $case->cid;
    $form['target_bundle']['#value'] = $case->type;
    $form['target_entity']['#value'] = 'crm_case';
  }
  if($node = menu_get_object('node')) {
    $form['target_id']['#value'] = $node->nid;
    $form['target_bundle']['#value'] = $node->type;
    $form['target_entity']['#value'] = 'node';
  }
  
  if(user_access('create tasks for other users')) {
    global $user;
    $form['assigned_user'] = array(
      '#type' => 'textfield',
      '#title' => 'Assign to someone else',
      '#default_value' => strip_tags(theme('username', array('account' => $user, 'link_path' => FALSE))),
      '#autocomplete_path' => 'ajax/crm/tasks/user-autocomplete',
    );
  }
  
  $form['date'] = array(
    '#type' => 'date_popup',
    '#title' => 'Due date',
    '#date_format' => 'Y-m-d',
  );
  
  $form['note'] = array(
    '#type' => 'textfield',
    '#title' => 'Note',
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save task',
  );
  
  $form['cancel'] = array(
    '#markup' => l('Cancel', '', array('fragment' => 'task-cancel', 'external' => TRUE, 'attributes' => array('id' => 'task-cancel'))),
  );
  
  return $form;
}

/**
 * Create task form submit
 */
function crm_tasks_create_task_form_submit($form, $form_state) {
  if($form_state['values']['assigned_user']) {
    $uid = db_select('users')->fields('users', array('uid'))->condition('name', $form_state['values']['assigned_user'])->execute()->fetchField();
    $target_user = user_load($uid);
  }
  else {
    global $user;
    $target_user = $user;
  }
  $relation = relation_create('crm_task', array(
                  array('entity_type' => 'user',
                         'entity_bundle' => 'user',
                         'entity_id' => $target_user->uid,
                         'r_index' => 0,
                         ),
                  array('entity_type' => $form_state['values']['target_entity'],
                         'entity_bundle' => $form_state['values']['target_bundle'], 
                         'entity_id' => $form_state['values']['target_id'],
                         'r_index' => 1,
                         ))
               );
  $rid = relation_save($relation);
  $relation = relation_load($rid);
  $language = ($relation->language) ? $relation->language : LANGUAGE_NONE;
  $relation->field_task_due[$language][0]['value'] = $form_state['values']['date'];
  $relation->field_task_note[$language][0]['value'] = $form_state['values']['note'];
  relation_save($relation);
  drupal_set_message(t('Your task has been created.'));
}

/**
 * Implements hook_permission().
 */
function crm_tasks_permission() {
  return array(
    'maintain own task list' => array(
      'title' => t('Maintain own task list'),
      'description' => t('User can add and maintain their own list of tasks.'),
    ),
    'create tasks for other users' => array(
      'title' => t('Create tasks for other users'),
      'description' => t('User can add tasks to the lists of other users.'),
    ),
  );
}