<?php
/**
 * @file
 * Code for the Student CRM Holds feature.
 */

include_once('student_crm_holds.features.inc');

/**
 * Implements hook_feeds_plugins().
 */
function student_crm_holds_feeds_plugins() {
  $info['CRMFeedsHoldsProcessor'] = array(
    'name' => 'Student Holds processor',
    'description' => 'Add and update student hold records.',
    'help' => 'Create and update hold records from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'CRMFeedsHoldsProcessor',
      'file' => 'CRMFeedsHoldsProcessor.inc',
      'path' => drupal_get_path('module', 'student_crm_holds') . '/plugins',
    ),
  );
  return $info;
}

/*
 * Implements hook_enable().
 */
function student_crm_holds_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}